version: '3'

services:
  webapp:
    image: docker-react:1.0
    build:
      context: ./webapp
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - redis
    environment:
      - FLASK_APP=app.py

  redis:
    image: "redis:latest"
